drop database if exists drinksapi;

create database if not exists drinksapi;

use drinksapi;

CREATE TABLE if not exists `drink_table` (
  `id` int(11) NOT NULL,
  `name` varchar(256) NOT NULL,
  `category` varchar(256) NOT NULL,
  `alcoholic` varchar(256) NOT NULL,
  `glass` varchar(256) NOT NULL,
  `instructions` text NOT NULL,
  `photo_url` varchar(1000) NOT NULL,
  `ingredient1` varchar(256),
  `ingredient2` varchar(256),
  `ingredient3` varchar(256),
  `ingredient4` varchar(256),
  `ingredient5` varchar(256),
  `ingredient6` varchar(256),
  `ingredient7` varchar(256),
  `ingredient8` varchar(256),
  `ingredient9` varchar(256),
  `ingredient10` varchar(256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO drink_table VALUES (
    17222,
    'A1',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
    'photos/2x8thr1504816928.jpg',
    'Gin',
    'Grand Marnier',
    'Lemon Juice',
    'Grenadine',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13501,
    'ABC',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Layered in a shot glass.',
    'photos/tqpvqp1472668328.jpg',
    'Amaretto',
    'Baileys irish cream',
    'Cognac',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17225,
    'Ace',
    'Cocktail',
    'Alcoholic',
    'Martini Glass',
    'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
    'photos/l3cd7f1504818306.jpg',
    'Gin',
    'Grenadine',
    'Heavy cream',
    'Milk',
    'Egg White',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14610,
    'ACID',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
    'photos/xuxpxt1479209317.jpg',
    '151 proof rum',
    'Wild Turkey',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17228,
    'Addison',
    'Cocktail',
    'Alcoholic',
    'Martini Glass',
    'Shake together all the ingredients and strain into a cold glass.',
    'photos/yzva7x1504820300.jpg',
    'Gin',
    'Vermouth',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15853,
    'B-52',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Layer ingredients into a shot glass. Serve with a stirrer.',
    'photos/5a3vg61504372070.jpg',
    'Baileys irish cream',
    'Grand Marnier',
    'Kahlua',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13332,
    'B-53',
    'Shot',
    'Alcoholic',
    'Collins Glass',
    'Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',
    'photos/rwqxrv1461866023.jpg',
    'Kahlua',
    'Sambuca',
    'Grand Marnier',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17254,
    'Bijou',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Stir in mixing glass with ice and strain
',
    'photos/rysb3r1513706985.jpg',
    'Orange Bitters',
    'Green Chartreuse',
    'Gin',
    'Sweet Vermouth',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13222,
    'Big Red',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Pour ingredients into 1 ounce shot glass',
    'photos/yqwuwu1441248116.jpg',
    'Irish cream',
    'Goldschlager',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178310,
    'Brooklyn',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Combine ingredients with ice and stir until well-chilled. Strain into a chilled cocktail glass.',
    'photos/ojsezf1582477277.jpg',
    'Rye Whiskey',
    'Dry Vermouth',
    'Maraschino Liqueur',
    'Angostura Bitters',
    'Maraschino Cherry',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14608,
    'Cream Soda',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Pour 1oz of Spiced Rum into a highball glass with ice. Fill with Ginger Ale.',
    'photos/yqstxr1479209367.jpg',
    'Spiced rum',
    'Ginger ale',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17830,
    'Corn n Oil',
    'Cocktail',
    'Alcoholic',
    'Old-fashioned glass',
    'Cut the half lime in half again. Add the lime, falernum, and bitters to a rocks glass. Muddle. Add the rum. (Aged Barbados rum such as Plantation 5 Year is recommended). Add ice and stir. Float the blackstrap rum on top. Serve with a straw.',
    'photos/pk6dwi1592767243.jpg',
    'Lime',
    'Falernum',
    'Angostura Bitters',
    'Añejo rum',
    'blackstrap rum',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16047,
    'Campari Beer',
    'Beer',
    'Alcoholic',
    'Beer mug',
    'Use a 15 oz glass. Add Campari first. Fill with beer.',
    'photos/xsqrup1441249130.jpg',
    'Lager',
    'Campari',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17196,
    'Cosmopolitan',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.',
    'photos/kpsajh1504368362.jpg',
    'Vodka',
    'Lime juice',
    'Cointreau',
    'Cranberry juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17250,
    'Corpse Reviver',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake, strain, straight up, cocktail glass rinsed with absinthe
',
    'photos/gifgao1513704334.jpg',
    'Gin',
    'Triple Sec',
    'Lillet Blanc',
    'Lemon Juice',
    'Absinthe',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13128,
    'Diesel',
    'Beer',
    'Alcoholic',
    'Pint glass',
    'Pour the lager first then add the blackcurrant cordial. Top up with the cider. The colour sholud be very dark approaching the colour of Guiness.',
    'photos/sxrrqq1454512852.jpg',
    'Lager',
    'Cider',
    'Blackcurrant cordial',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    11005,
    'Dry Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    'photos/6ck9yi1589574317.jpg',
    'Gin',
    'Dry Vermouth',
    'Olive',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14466,
    'Dirty Nipple',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'This is a layered shot - the Bailey''s must be on top',
    'photos/vtyqrt1461866508.jpg',
    'Kahlua',
    'Sambuca',
    'Baileys irish cream',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17181,
    'Dirty Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Pour the vodka, dry vermouth and olive brine into a cocktail shaker with a handful of ice and shake well.
Rub the rim of a martini glass with the wedge of lemon.
Strain the contents of the cocktail shaker into the glass and add the olive.
A dirty Martini contains a splash of olive brine or olive juice and is typically garnished with an olive.',
    'photos/vcyvpq1485083300.jpg',
    'Vodka',
    'Dry Vermouth',
    'Olive Brine',
    'Lemon',
    'Olive',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17177,
    'Dark Caipirinha',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Muddle the sugar into the lime wedges in an old-fashioned glass.
Fill the glass with ice cubes.
Pour the cachaca into the glass.
Stir well.',
    'photos/uwstrx1472406058.jpg',
    'demerara Sugar',
    'Lime',
    'Cachaca',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17212,
    'Espresso Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Pour ingredients into shaker filled with ice, shake vigorously, and strain into chilled martini glass',
    'photos/n0sx531504372951.jpg',
    'Vodka',
    'Kahlua',
    'Sugar syrup',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178309,
    'Espresso Rumtini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Mix together in a cocktail glass. Garnish with some choclate powder and coffee beans',
    'photos/acvf171561574403.jpg',
    'Rum',
    'Vanilla syrup',
    'Espresso',
    'Coffee',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178346,
    'Elderflower Caipirinha',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Take the glass and muddle the lime in it. Fill the glass with crushed ice and add the Cachaca. Stir well and top with some more crushed ice. Garnish with lime and enjoy!',
    'photos/dif7a31614006331.jpg',
    'Cachaca',
    'Lime',
    'Elderflower cordial',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17246,
    'Empellón Cocina''s Fat-Washed Mezcal',
    'Cocktail',
    'Alcoholic',
    'Beer Glass',
    'To ensure that your pork fat is just as delicious as theirs, here’s their adobo marinade and what to do with it (you’ll also need a rack of ribs):

4 ancho chiles, 8 guajillo chiles and 4 chipotle chiles, plus 4 cloves roasted garlic, half a cup of cider vinegar, a quarter teaspoon of Mexican oregano, 1 teaspoon of ground black pepper, a whole clove, a quarter teaspoon of ground cinnamon and a half teaspoon of ground cumin.

Toast the dried chiles and soak in water for at least an hour until they are rehydrated. Drain and discard the soaking liquid. Combine the soaked chiles with the remaining ingredients and purée until smooth.

Cold smoke a rack of baby back pork ribs by taking a large hotel pan with woodchips on one side and charcoal on the other. Place another, smaller, pan with pork ribs, above the charcoal/woodchip pan. Ignite the charcoal, being careful to not ignite the woodchips. Cover both pans with foil and allow to smoke for 10-15 minutes, until desired level of smoke is achieved, then coat with adobo marinade and wrap in tin foil prior to placing ribs in a 300 degree oven for 7 hours. When the ribs have cooled, strain off the fat and use for the infusion.

If you’re having a hard time coming up to the same kind of volume of fat, make up the balance with pork lard from a butcher. To get the same depth of flavor without the ribs, heat up the fat in a pot with a few spoons of the marinade.

Once you’ve got your tub of seasoned pork fat in cooled liquid form, pour equal amounts of Ilegal Joven mezcal and fat into a sealable container. Seal the container and give it a really good shake, then put it in the freezer overnight. When the whole thing is separated and congealed, pour it through a fine mesh chinoise. If you don’t have a chinoise, try a fine mesh strainer, or if you don’t have one of those, try spooning off most of the fat. There will be some beads of orange fat left in the strained mezcal: run that through a few layers of cheesecloth (or coffee filters in a pinch) to get rid of the last of it.

The mezcal is now ready for drinking, straight-up or in a cocktail. 

Habanero tincture

Slice habaneros and add 2 ounces Ilegal Joven mezcal.
Allow to sit overnight or until desired level of heat is achieved.
Cocktail

Combine mezcal and chocolate liqueur in a mixing glass with ice and stir for 45 seconds.
Strain into chilled coupe.
Carefully "sink" the coffee liqueur down the inside of the coupe over a spoon.
Garnish with 5 drops habanero tincture.',
    'photos/osgvxt1513595509.jpg',
    'Mezcal',
    'Chocolate liqueur',
    'Coffee liqueur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178352,
    'Frosé',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Step 1
Pour rosé into a 13x9" pan and freeze until almost solid (it won''t completely solidify due to the alcohol), at least 6 hours.

Step 2
Meanwhile, bring sugar and ½ cup water to a boil in a medium saucepan; cook, stirring constantly, until sugar dissolves, about 3 minutes. Add strawberries, remove from heat, and let sit 30 minutes to infuse syrup with strawberry flavor. Strain through a fine-mesh sieve into a small bowl (do not press on solids); cover and chill until cold, about 30 minutes.

Step 3
Scrape rosé into a blender. Add lemon juice, 3½ ounces strawberry syrup, and 1 cup crushed ice and purée until smooth. Transfer blender jar to freezer and freeze until frosé is thickened (aim for milkshake consistency), 25–35 minutes.

Step 4
Blend again until frosé is slushy. Divide among glasses.

Step 5
Do Ahead: Rosé can be frozen 1 week ahead.',
    'photos/b4cadp1619695347.jpg',
    'Rose',
    'Sugar',
    'Strawberries',
    'Lemon Juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178344,
    'Figgy Thyme',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'In a lewis bag, crush up some ice like a baller/maniac (@glacioice). Pour your precious ice into a collins glass. In a cocktail shaker, muddle the figs and thyme together. Add honey vodka, lemon juice, and a large ice cube (@glacioice). Shake until well chilled, and strain into glass. Add tonic water and finally 2 dashes of angostura bitters. Garnish with sliced figs and thyme.',
    'photos/pbw4e51606766578.jpg',
    'Vodka',
    'Honey',
    'Figs',
    'Thyme',
    'Angostura Bitters',
    'Tonic Water',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14688,
    'Freddy Kruger',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'make it an ample size shot!!',
    'photos/tuppuq1461866798.jpg',
    'Jägermeister',
    'Sambuca',
    'Vodka',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178328,
    'Funk and Soul',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Mix all ingredients together and strain into a Collins glass. Use Jamaican rum where possible for a more authentic taste.',
    'photos/qtv83q1596015790.jpg',
    'Rum',
    'Apricot Nectar',
    'Pomegranate juice',
    'lemon',
    'Soda Water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17213,
    'French Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Pour all ingredients into shaker with ice cubes. Shake well and strain into a chilled cocktail glass. Squeeze oil from lemon peel onto the drink.',
    'photos/clth721504373134.jpg',
    'Vodka',
    'Raspberry Liqueur',
    'pineapple juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17255,
    'Gimlet',
    'Cocktail',
    'Alcoholic',
    'Martini Glass',
    'Add all the ingredients to a shaker and fill with ice.

Shake, and strain into a chilled cocktail glass or an Old Fashioned glass filled with fresh ice.

Garnish with a lime wheel.',
    'photos/3xgldt1513707271.jpg',
    'Gin',
    'Lime Juice',
    'Sugar Syrup',
    'Lime',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    12758,
    'Gagliardo',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake well and serve in a cocktail glass. This is a home cocktail of American/Internet Bar del Pozzo, Pavia, Italy.',
    'photos/lyloe91487602877.jpg',
    'Peach Vodka',
    'Lemon juice',
    'Galliano',
    'Sirup of roses',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178365,
    'Gin Tonic',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Fill a highball glass with ice, pour the gin, top with tonic water and squeeze a lemon wedge and garnish with a lemon wedge.',
    'photos/qcgz0t1643821443.jpg',
    'Gin',
    'Tonic Water',
    'Lemon Peel',
    'Ice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178366,
    'Gin Lemon',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'For the preparation of the gin lemon you will not need the shaker. Fill the tumbler with ice, pour the gin and lemonade over it. Gently mix and decorate with a slice of lemon. Those who prefer can also add a few mint leaves. Your gin lemon is ready to be served.',
    'photos/6gdohq1681212476.jpg',
    'Gin',
    'Lemon Juice',
    'Lemon Peel',
    'Ice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17252,
    'Greyhound',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Add the vodka to a Collins glass filled with ice.
Top with grapefruit juice and stir.

',
    'photos/g5upn41513706732.jpg',
    'Vodka',
    'Grapefruit Juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178316,
    'Honey Bee',
    'Cocktail',
    'Alcoholic',
    'Margarita glass',
    'Shake ingredients with crushed ice
',
    'photos/vu8l7t1582475673.jpg',
    'White Rum',
    'Honey',
    'Lemon Juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178345,
    'Hot Toddy',
    'Cocktail',
    'Alcoholic',
    'Irish coffee cup',
    'STEP 1
Whisk the whisky and honey together and split between 2 heatproof glasses. Add half of the cinnamon stick to each, then top up with 200ml boiling water.

STEP 2
Add a splash of lemon juice to each, then taste and add more to your preference. Finish each with a slice of lemon, studded with a clove, and serve immediately.',
    'photos/ggx0lv1613942306.jpg',
    'Whiskey',
    'Honey',
    'Cinnamon',
    'lemon',
    'Cloves',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17239,
    'Hunter''s Moon',
    'Cocktail',
    'Alcoholic',
    'Balloon Glass',
    'Put the Bombay Sapphire, Martini Bianco, sugar syrup & blackberries in a cocktail shaker with lots of ice and shake vigorously before pouring into a balloon glass, topping up with lemonade and garnishing with a wedge of orange.',
    'photos/t0iugg1509556712.jpg',
    'Vermouth',
    'Maraschino Cherry',
    'Sugar Syrup',
    'Lemonade',
    'Blackberries',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17015,
    'Irish Russian',
    'Beer',
    'Alcoholic',
    'Highball glass',
    'Add the ingredients in the order listed in the recipe. Care must be taken when adding the Guinness to prevent an excess of foam. Do Not add ice.',
    'photos/swqurw1454512730.jpg',
    'Vodka',
    'Kahlua',
    'Coca-Cola',
    'Guinness stout',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    12706,
    'Imperial Cocktail',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake with ice and strain into cocktail glass.',
    'photos/bcsj2e1487603625.jpg',
    'Lime juice',
    'Gin',
    'Aperol',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16987,
    'Irish Curdling Cow',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Pour Irish Cream, Vodka, and Bourbon in a glass. Add some ice and mix in the orange juice.',
    'photos/yrhutv1503563730.jpg',
    'Baileys irish cream',
    'Bourbon',
    'Vodka',
    'Orange juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17178,
    'Jam Donut',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Coat the rim of a shot glass with sugar using sugar syrup to stick. Add the Chambord raspberry liqueur to the shot glass, and carefully layer the Baileys Irish Cream on top. Serve.',
    'photos/uuytrp1474039804.jpg',
    'Baileys irish cream',
    'Chambord raspberry liqueur',
    'Sugar syrup',
    'Sugar',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16178,
    'Jitterbug',
    'Cocktail',
    'Alcoholic',
    'Cocktail Glass',
    'Wet glass, dip rim in sugar. Then add Ice. Then add everything else. It''s that simple!',
    'photos/wwqvrq1441245318.jpg',
    'Gin',
    'Vodka',
    'Grenadine',
    'Lime juice',
    'Sugar',
    'Sugar syrup',
    'Soda water',
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13775,
    'Jelly Bean',
    'Shot',
    'Alcoholic',
    'Cordial glass',
    'mix equal parts in pony glass-tastes just like a jelly bean!',
    'photos/bglc6y1504388797.jpg',
    'Blackberry brandy',
    'Anis',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14956,
    'Jello shots',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Boil 3 cups of water then add jello. Mix jello and water until jello is completely disolved. Add the two cups of vodka and mix together. Pour mixture into plastic shot glasses and chill until firm. Then, eat away...',
    'photos/l0smzo1504884904.jpg',
    'Vodka',
    'Jello',
    'Water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14095,
    'Jamaica Kiss',
    'Shake',
    'Alcoholic',
    'Hurricane glass',
    'Fill a tumbler with ice cubes. Add a shot of Tia Maria and a shot of Jamaican light rum. Fill the tumbler with milk. Blend until smooth and serve immediately.',
    'photos/urpvvv1441249549.jpg',
    'Coffee liqueur',
    'Light rum',
    'Ice',
    'Milk',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178359,
    'Kiwi Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'The kiwi martini is a very fun vodka cocktail and it is one of the best drinks that makes use of fresh fruit. Though there are a few recipes floating around, this is one of the easiest and it is an absolutely delightful green martini to drink.

For this recipe, you''ll simply muddle slices of kiwi with simple syrup, then shake it with vodka. It''s a drink that anyone can mix up in minutes and a perfect cocktail to show off your favorite vodka.',
    'photos/bmxmyq1630407098.jpg',
    'Kiwi',
    'Sugar Syrup',
    'Vodka',
    'Kiwi',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13190,
    'Kool-Aid Shot',
    'Shot',
    'Alcoholic',
    'Old-fashioned glass',
    'Pour into a large glass with ice and stir. Add a little cranberry juice to taste.',
    'photos/fegm621503564966.jpg',
    'Vodka',
    'Amaretto',
    'Sloe gin',
    'Triple sec',
    'Cranberry juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17006,
    'Kool First Aid',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Add Kool Aid to a double shot glass, and top with rum. Slam and shoot.',
    'photos/hfp6sv1503564824.jpg',
    '151 proof rum',
    'Kool-Aid',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14446,
    'Kool-Aid Slammer',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Fill half the shot glass with the kool-aid first. Then put a paper towel over the top of the glass and slowly pour in the vodka. If you do it right, you should be able to see that the two liquids are separated, with the vodka on top. Now slam it! The last thing you''ll taste is the kool-aid.',
    'photos/kugu2m1504735473.jpg',
    'Kool-Aid',
    'Vodka',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14378,
    'Lunch Box',
    'Beer',
    'Alcoholic',
    'Pint glass',
    'Fill a pint glass almost full with beer. Then fill the rest with orange juice (careful not to fill it to the top). Then take the shot of Amaretto and drop it in.',
    'photos/qywpvt1454512546.jpg',
    'Beer',
    'Amaretto',
    'Orange juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14366,
    'Lemon Drop',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake and strain into a chilled cocktail glass rimmed with sugar.',
    'photos/mtpxgk1504373297.jpg',
    'Vodka',
    'Cointreau',
    'Lemon',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    12752,
    'Lemon Shot',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Mix Galliano and Absolut Citron in a shot glass, lay lemon wedge sprinkled with sugar over glass and pour a rum over wedge and glass. light rum with a lighter and let burn for a second. Do shot quickly and suck on lemon. If it is done correctly, this will taste like a shot of sweet lemonade.',
    'photos/mx31hv1487602979.jpg',
    'Galliano',
    'Absolut Citron',
    'Lemon',
    'Sugar',
    '151 proof rum',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15086,
    'Limona Corona',
    'Beer',
    'Alcoholic',
    'Beer Glass',
    'Open the Corona. Fill the empty space in the neck in the bottle with the rum. The bottle should be filled to the top. Plug the bottle with your thumb or the palm of your hand. Turn the bottle upside-down so the rum and beer mix. Turn the bottle rightside-up, unplug, and drink.',
    'photos/wwqrsw1441248662.jpg',
    'Corona',
    'Bacardi Limon',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178335,
    'Lazy Coconut Paloma',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Mix the coconut liqueur (preferably tequila) with the grapefruit juice and top with soda water. Garnish with a large grapefruit slice against the inside of the glass.',
    'photos/rytuex1598719770.jpg',
    'Coconut Liqueur',
    'Grapefruit Juice',
    'Soda Water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    11000,
    'Mojito',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
    'photos/metwgh1606770327.jpg',
    'Light rum',
    'Lime',
    'Sugar',
    'Mint',
    'Soda water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    11728,
    'Martini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    'photos/71t8581504353095.jpg',
    'Gin',
    'Dry Vermouth',
    'Olive',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178343,
    'Michelada',
    'Cocktail',
    'Alcoholic',
    'Pint glass',
    'Mix the beer with tomato juice, freshly squeezed lime juice, and Worcestershire sauce, teriyaki sauce, soy sauce, or hot sauce.
Served In a chilled, salt-rimmed glass
',
    'photos/u736bd1605907086.jpg',
    'Beer',
    'Tomato Juice',
    'Lime Juice',
    'Hot Sauce',
    'Worcestershire Sauce',
    'Soy Sauce',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    11008,
    'Manhattan',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Stirred over ice, strained into a chilled glass, garnished, and served up.',
    'photos/yk70e31606771240.jpg',
    'Sweet Vermouth',
    'Bourbon',
    'Angostura bitters',
    'Ice',
    'Maraschino cherry',
    'Orange peel',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178370,
    'Mauresque',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    '1 - Pour the Ricard (or pastis)
2 - Pour the orgeat syrup
3 - Finally pour the water and add ice cubes at your convenience.

Add the ice cubes at the end, otherwise the syrup and pastis do not mix well.',
    'photos/duwfa11686236556.jpg',
    'Ricard',
    'Orgeat Syrup',
    'Water',
    '',
    '',
    '',
    '',
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13861,
    'Nutty Irishman',
    'Shake',
    'Alcoholic',
    'Highball Glass',
    'Serve over ice',
    'photos/xspupx1441248014.jpg',
    'Baileys irish cream',
    'Frangelico',
    'Milk',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13204,
    'New York Lemonade',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Serve in a chilled cocktail glass. Lemon and sugar the rim. Stir and Strain.',
    'photos/b3n0ge1503565473.jpg',
    'Absolut Citron',
    'Grand Marnier',
    'Lemon juice',
    'Club soda',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17827,
    'Old Pal',
    'Cocktail',
    'Alcoholic',
    'Nick and Nora Glass',
    'Chill cocktail glass. Add ingredients to a mixing glass, and fill 2/3 full with ice. Stir about 20 seconds. Empty cocktail glass and strain into the glass. Garnish with a twist of lemon peel.',
    'photos/x03td31521761009.jpg',
    'Rye whiskey',
    'Campari',
    'Dry Vermouth',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178371,
    'Old Cuban',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake a handful of mint, 2oz white rum, 1oz of sugar syrup, 1oz lime juice and 2 dashes angostura bitters with ice. Double strain into a glass and top with 2oz of prosecco.',
    'photos/eo8gfx1699022995.jpg',
    'White Rum',
    'Sugar Syrup',
    'Lime Juice',
    'Angostura Bitters',
    'Prosecco',
    '',
    '',
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    12618,
    'Orangeade',
    'Cocktail',
    'Non alcoholic',
    'Highball glass',
    'Place some ice cubes in a large tumbler or highball glass, add lemon juice, orange juice, sugar syrup, and stir well. Top up with cold soda water, serve with a drinking straw.',
    'photos/ytsxxw1441167732.jpg',
    'Lemon juice',
    'Orange juice',
    'Sugar syrup',
    'Soda water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15330,
    'Orange Crush',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Add all ingredients to tumbler-Pour as shot',
    'photos/zvoics1504885926.jpg',
    'Vodka',
    'Triple sec',
    'Orange juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    11001,
    'Old Fashioned',
    'Cocktail',
    'Alcoholic',
    'Old-fashioned glass',
    'Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.
Fill the glass with ice cubes and add whiskey.

Garnish with orange twist, and a cocktail cherry.',
    'photos/vrwquq1478252802.jpg',
    'Bourbon',
    'Angostura bitters',
    'Sugar',
    'Water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17253,
    'Paloma',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Stir together and serve over ice.',
    'photos/samm5j1513706393.jpg',
    'Grape Soda',
    'Tequila',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17249,
    'Pegu Club',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake, strain, up, cocktail glass',
    'photos/jfkemm1513703902.jpg',
    'Gin',
    'Orange Curacao',
    'Lime Juice',
    'Angostura Bitters',
    'Orange Bitters',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178354,
    'Pink Moon',
    'Cocktail',
    'Alcoholic',
    'Whiskey Glass',
    'Slowly shake in a shaker with ice, strain into a square whiskey glass. Top with fresh ice. Add the blackberries to garnish. Add flowers and a green leaf for a special look!',
    'photos/lnjoc81619696191.jpg',
    'Gin',
    'Coconut Liqueur',
    'Elderflower cordial',
    'Lime Juice',
    'Blackberries',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17829,
    'Penicillin',
    'Cocktail',
    'Alcoholic',
    'Old-fashioned glass',
    'Shake blended Scotch, lemon juice, honey syrup and ginger syrup with ice. Strain over large ice in chilled rocks glass. Float smoky Scotch on top (be sure to use a smoky Scotch such as an Islay single malt). Garnish with candied ginger.',
    'photos/hc9b1a1521853096.jpg',
    'Blended Scotch',
    'Lemon Juice',
    'Honey syrup',
    'Ginger Syrup',
    'Islay single malt Scotch',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13214,
    'Pisco Sour',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Vigorously shake and strain contents in a cocktail shaker with ice cubes, then pour into glass and garnish with bitters.
',
    'photos/tsssur1439907622.jpg',
    'Pisco',
    'Lemon juice',
    'Sugar',
    'Ice',
    'Egg White',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    13198,
    'Quick F**K',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'In a shot glass add 1/3 Kahlua first. Then 1/3 Miduri, topping it off with a 1/3 bailey''s irish cream',
    'photos/wvtwpp1478963454.jpg',
    'Kahlua',
    'Midori melon liqueur',
    'Baileys irish cream',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14087,
    'Red Snapper',
    'Shot',
    'Alcoholic',
    'Old-fashioned glass',
    'One shot each, shake n shoot',
    'photos/7p607y1504735343.jpg',
    'Crown Royal',
    'Amaretto',
    'Cranberry juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17122,
    'Royal Bitch',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Into a shot glass layer the Crown Royal on top of the Frangelico.',
    'photos/qupuyr1441210090.jpg',
    'Frangelico',
    'Crown Royal',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15082,
    'Royal Flush',
    'Shot',
    'Alcoholic',
    'Old-fashioned glass',
    'Pour all the ingredients into tumbler over ice. Strain into glass.',
    'photos/7rnm8u1504888527.jpg',
    'Crown Royal',
    'Peach schnapps',
    'Chambord raspberry liqueur',
    'Cranberry juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17114,
    'Ruby Tuesday',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Pour gin and cranberry into a highball filled with ice cubes. Add grenadine and stir.',
    'photos/qsyqqq1441553437.jpg',
    'Gin',
    'Cranberry juice',
    'Grenadine',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    12630,
    'Rail Splitter',
    'Cocktail',
    'Non alcoholic',
    'Highball glass',
    'Mix sugar syrup with lemon juice in a tall glass. Fill up with ginger ale.',
    'photos/stsuqq1441207660.jpg',
    'Sugar syrup',
    'Lemon juice',
    'Ginger ale',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178349,
    'Snowday',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Stir all ingredients with ice. Strain into a chilled rocks glass over fresh ice. Express orange peel over drink and garnish.',
    'photos/4n1ipk1614009624.jpg',
    'Vodka',
    'Amaro Montenegro',
    'Ruby Port',
    'Blood Orange',
    'Angostura Bitters',
    'Orange Peel',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178322,
    'Spice 75',
    'Cocktail',
    'Alcoholic',
    'Wine Glass',
    'Gently warm 60g golden caster sugar in a pan with 30ml water and 1 tbsp allspice. Cook gently until the sugar has dissolved, then leave the mixture to cool. Strain through a sieve lined with a coffee filter (or a double layer of kitchen paper).

Pour 60ml of the spiced syrup into a cocktail shaker along with 200ml rum and 90ml lime juice. Shake with ice and strain between six flute glasses. Top up with 600ml champagne and garnish each with an orange twist.',
    'photos/0108c41576797064.jpg',
    'Sugar',
    'Allspice',
    'Rum',
    'Lime Juice',
    'Champagne',
    'Orange spiral',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16985,
    'Shot-gun',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Pour one part Jack Daneils and one part Jim Beam into shot glass then float Wild Turkey on top.',
    'photos/2j1m881503563583.jpg',
    'Jim Beam',
    'Jack Daniels',
    'Wild Turkey',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16990,
    'Sweet Tooth',
    'Shake',
    'Alcoholic',
    'Highball Glass',
    'Put 2 shots Godiva Liquour into a glass, add as much or as little milk as you would like.',
    'photos/j6rq6h1503563821.jpg',
    'Godiva liqueur',
    'Milk',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16273,
    'Shark Attack',
    'Cocktail',
    'Alcoholic',
    'Pitcher',
    'Mix lemonade and water according to instructions on back of can. If the instructions say to add 4 1/3 cans of water do so. Mix into pitcher. Add 1 1/2 cup of Vodka (Absolut). Mix well. Pour into glass of crushed ice. Excellent!',
    'photos/uv96zr1504793256.jpg',
    'Lemonade',
    'Water',
    'Vodka',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178350,
    'The Galah',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    'Mix together the alcoholic portions and top with Pineapple and Lime juice.',
    'photos/sy7y6r1614775067.jpg',
    'Dark Rum',
    'Campari',
    'Creme De Banane',
    'Pineapple Juice',
    'Lime Juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17828,
    'Tipperary',
    'Cocktail',
    'Alcoholic',
    'Nick and Nora Glass',
    'Stir over ice. Strain into chilled glass. Cut a wide swath of orange peel, and express the orange oils over the drink. Discard orange twist.',
    'photos/b522ek1521761610.jpg',
    'Irish Whiskey',
    'Sweet Vermouth',
    'Green Chartreuse',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15006,
    'Turkeyball',
    'Shot',
    'Alcoholic',
    'Shot glass',
    'Shake with ice and strain into a shot glass.',
    'photos/rxurpr1441554292.jpg',
    'Wild Turkey',
    'Amaretto',
    'Pineapple juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    15639,
    'Texas Sling',
    'Shake',
    'Alcoholic',
    'Wine Glass',
    'Blend with Ice until smooth. Serve in a tulip glass, top with whip cream.',
    'photos/ypl13s1504890158.jpg',
    'Kahlua',
    'Irish cream',
    'Amaretto',
    '151 proof rum',
    'Cream',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17247,
    'The Last Word',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake with ice and strain into a cocktail glass.',
    'photos/91oule1513702624.jpg',
    'Green Chartreuse',
    'Maraschino Liqueur',
    'Lime Juice',
    'Gin',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17218,
    'Vesper',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake over ice until well chilled, then strain into a deep goblet and garnish with a thin slice of lemon peel.',
    'photos/mtdxpa1504374514.jpg',
    'Gin',
    'Vodka',
    'Lillet Blanc',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178363,
    'Vodka Lemon',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'The vodka lemon is prepared directly in a highball glass or in a large tumbler: put 6-7 ice cubes in the glass, pour the vodka, lemonade and mix with a bar spoon. Finally decorate with a slice of lemon and, if you prefer, add a few mint leaves. Your vodka lemon is ready to be served.',
    'photos/mql55h1643820632.jpg',
    'Vodka',
    'Lemon Juice',
    'Lemon Peel',
    'Ice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178362,
    'Vodka Slime',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Fill glass with ice. Add vodka, 7-up then finish with the lime juice.',
    'photos/apex461643588115.jpg',
    'Sprite',
    'Lime Juice',
    'Vodka',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178364,
    'Vodka Tonic',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Wash and cut 1 wedge and 1 slice of lime or lemon.
Fill a tumbler with fresh ice.
Pour the desired dose of vodka and top up with the tonic.
Squeeze the lime wedge into the glass and decorate with the slice.
That''s all, very simple: it''s just the recipe for happiness!',
    'photos/9koz3f1643821062.jpg',
    'Vodka',
    'Tonic Water',
    'Lemon Peel',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178347,
    'Winter Rita',
    'Beer',
    'Alcoholic',
    'Highball Glass',
    'Salt rim. Combine all ingredients, shake with ice, and strain over fresh ice.⠀',
    'photos/fwpd0v1614006733.jpg',
    'Tequila',
    'Campari',
    'Lime Juice',
    'Orange Juice',
    'Rosemary Syrup',
    'Salt',
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    178348,
    'Winter Paloma',
    'Cocktail',
    'Alcoholic',
    'Highball glass',
    'Everyone’s favourite Paloma gets a delicious Indian makeover. Tequila reposado infused with “Timur Pepper” which has citrusy & grapefruit notes and is grown at the foothills of Himalaya. It also produces a slightly numbing and tingling sensation on your lip when consumed. We have also spiced up the fresh grapefruit juice with the warming spice blend from Himalaya. The combination of all these interesting elements has allowed us to elevate your Paloma sipping experience.',
    'photos/u5f0pz1614007748.jpg',
    'Tequila',
    'Grapefruit Juice',
    'Lime Juice',
    'Agave Syrup',
    'Pepper',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17219,
    'Yellow Bird',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Shake and strain into a chilled cocktail glass',
    'photos/2t9r6w1504374811.jpg',
    'White Rum',
    'Galliano',
    'Triple Sec',
    'Lime Juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    17241,
    'Zombie',
    'Cocktail',
    'Alcoholic',
    'Hurricane glass',
    'Blend at high speed for no more than 5 seconds.

Pour into a glass, add ice cubes to fill, then add the garnish.

*Donn’s mix: Bring 3 crushed cinnamon sticks, 1 cup of sugar and 1 cup of water to a boil, stirring until the sugar is dissolved.

Simmer for 2 minutes, then remove from the heat and let sit for at least 2 hours before straining into a clean glass bottle.

Then add 1 part of the syrup and 2 parts of fresh grapefruit juice together.',
    'photos/2en3jk1509557725.jpg',
    'Rum',
    'Gold rum',
    '151 proof rum',
    'Pernod',
    'Grenadine',
    'Lime Juice',
    'Angostura Bitters',
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16963,
    'Zorbatini',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    'Prepare like a Martini. Garnish with a green olive.',
    'photos/wtkqgb1485621155.jpg',
    'Vodka',
    'Ouzo',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    16942,
    'Zipperhead',
    'Shot',
    'Alcoholic',
    'Whiskey sour glass',
    'Fill glass with rocks, add straw before putting in liquor. Then add the ingredients in order, trying to keep layered as much as possible (i.e. Chambord on bottom, then Vodka, Then soda on top).',
    'photos/r2qzhu1485620235.jpg',
    'Chambord raspberry liqueur',
    'Vodka',
    'Soda water',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
INSERT INTO drink_table VALUES (
    14065,
    'Zippy''s Revenge',
    'Cocktail',
    'Alcoholic',
    'Old-fashioned glass',
    'Mix Kool-Aid to taste then add Rum and ammaretto. shake well to disolve the sugar in the Kool-Aid... serve cold',
    'photos/1sqm7n1485620312.jpg',
    'Amaretto',
    'Rum',
    'Kool-Aid',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12776,
    'Melya',
    'Coffee',
    'Non alcoholic',
    'Coffee mug',
    "Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.",
    'photos/xwtptq1441247579.jpg',
    'Espresso',
    'Honey',
    'Cocoa powder',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12560,
    'Afterglow',
    'Cocktail',
    'Non alcoholic',
    'Highball Glass',
    "Mix. Serve over ice.",
    'photos/vuquyv1468876052.jpg',
    'Grenadine',
    'Orange juice',
    'Pineapple juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12724,
    'Sweet Bananas',
    'Shake',
    'Non alcoholic',
    'Highball Glass',
    "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.",
    'photos/sxpcj71487603345.jpg',
    'Milk',
    'Banana',
    'Honey',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12782,
    'Thai Coffee',
    'Coffee',
    'Non alcoholic',
    'Highball glass',
    "Place the coffee and spices in the filter cone of your coffee maker. Brew coffee as usual, let it cool. In a tall glass, dissolve 1 or 2 teaspoons of sugar in an ounce of the coffee (it's easier to dissolve than if you put it right over ice). Add 5-6 ice cubes and pour coffee to within about 1 inch of the top of the glass. Rest a spoon on top of the coffee and slowly pour whipping cream into the spoon. This will make the cream float on top of the coffee rather than dispersing into it right away.",
    'photos/wquwxs1441247025.jpg',
    'Coffee',
    'Coriander',
    'Cardamom',
    'Sugar',
    'Whipping cream',
    'Ice',
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12674,
    'Fruit Shake',
    'Other',
    'Non alcoholic',
    'Highball Glass',
    "Blend til smooth.",
    'photos/q0fg2m1484430704.jpg',
    'Yoghurt',
    'Banana',
    'Orange juice',
    'Fruit',
    'Ice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12670,
    'Fruit Cooler',
    'Other',
    'Non alcoholic',
    'Highball Glass',
    "Toss strawberries with sugar, and let sit overnight in refrigerator. Cut lemon, reserve two slices. Juice the rest. Mix together the lemon juice, strawberries, apple juice, and soda water. Add slices of lemon (decor, really). In glasses, put ice cubes, and a slice of apple. Pour drink in, and serve.",
    'photos/i3tfn31484430499.jpg',
    'Apple juice',
    'Strawberries',
    'Sugar',
    'Lemon',
    'Apple',
    'Soda water',
    'Ice',
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    16275,
    "Jack's Vanilla Coke",
    'Other',
    'Alcoholic',
    'Old-fashioned glass',
    "After pouring in your ingredients, and adding 3-5 ice cubes, according to taste. Stir the drink with a stirrer to get the Vanilla off the bottom.",
    'photos/kjnt7z1504793319.jpg',
    'Ice',
    'Tennessee whiskey',
    'Vanilla extract',
    'Coca-Cola',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12714,
    'Kiwi Papaya Smoothie',
    'Other',
    'Non alcoholic',
    'Highball Glass',
    "Throw everything into a blender and liquify.",
    'photos/jogv4w1487603571.jpg',
    'Kiwi',
    'Papaya',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12704,
    'Limeade',
    'Other',
    'Non alcoholic',
    'Highball glass',
    "In a large glass, put the lime juice and sugar, and stir well. Add cold seltzer water to fill. Put the lime peels in the glass. Drink. Repeat until limes or soda run out.",
    'photos/5jdp5r1487603680.jpg',
    'Lime',
    'Sugar',
    'Soda water',
    'Lime peel',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    178332,
    'Smashed Watermelon Margarita',
    'Cocktail',
    'Alcoholic',
    'Collins glass',
    "In a mason jar muddle the watermelon and 5 mint leaves together into a puree and strain. Next add the grapefruit juice, juice of half a lime and the tequila as well as some ice. Put a lid on the jar and shake. Pour into a glass and add more ice. Garnish with fresh mint and a small slice of watermelon.",
    'photos/dztcv51598717861.jpg',
    'Watermelon',
    'Mint',
    'Grapefruit Juice',
    'Lime',
    'Tequila',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    12322,
    'Strawberry Margarita',
    'Cocktail',
    'Alcoholic',
    'Cocktail glass',
    "Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.",
    'photos/tqyrpw1439905311.jpg',
    'Strawberry schnapps',
    'Tequila',
    'Triple sec',
    'Lemon juice',
    'Strawberries',
    'Salt',
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    11118,
    'Blue Margarita',
    'Other',
    'Alcoholic',
    'Cocktail glass',
    "Rub rim of cocktail glass with lime juice. Dip rim in coarse salt. Shake tequila, blue curacao, and lime juice with ice, strain into the salt-rimmed glass, and serve.",
    'photos/bry4qh1582751040.jpg',
    'Tequila',
    'Blue Curacao',
    'Lime juice',
    'Salt',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    16158,
    'Whitecap Margarita',
    'Other',
    'Alcoholic',
    'Margarita/Coupette glass',
    "Place all ingredients in a blender and blend until smooth. This makes one drink.",
    'photos/srpxxp1441209622.jpg',
    'Tequila',
    'Ice',
    'Cream of coconut',
    'Lime juice',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );
  INSERT INTO drink_table VALUES (
    17216,
    "Tommy's Margarita",
    'Other',
    'Non alcoholic',
    'Old-Fashioned glass',
    "Place all ingredients in a blender and blend until smooth. This makes one drink.",
    'photos/loezxn1504373874.jpg',
    'Mock Tequila',
    'Lime juice',
    'Agave syrup',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );